image: node:12
pipelines:
  default:
    - step:
        script:
          - npm install
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
          - docker build -t docker.io/karolscript/tnoradio:Posts .
          - docker push docker.io/karolscript/tnoradio:Posts
        services:
          - docker